### ISSUE TITLE
Create Mantis issue

### ISSUE THREAD

**Issue by TimThaler** [cyotek/MantisSharp#6]
Hello, 
and thanks for working on an up to date version of a Mantis client.
As stating in the README section:

> The REST API offered by MantisBT is also bit limited at the moment. It doesn't provide access to all information, and while you can create or delete issues (neither of which are offered by this library at the current time),

Is it possible as of today to create a new bug via this Client?
Cheers

**Comment by TimThaler** [comment]
Ah - just checked the closed issues now

**Comment by cyotek** [comment]
Hello,

Thanks for the question - I did update the library the other day to fix a silly bug but I haven't had much time to update it otherwise... it's been ticking along just fine so far. However I should at least update the readme to be accurate so thank you for pointing that out.

If you do use the library any feedback is welcome. I did have a bunch of MantisBT issues tagged for API improvements which have since been implemented so there's definitely more that _this_ library could do.

Regards;
Richard Moss
